// MIME类型映射配置
module.exports = {
  ".txt": "text/plain",
  ".md": "text/markdown",
  ".js": "text/javascript",
  ".py": "text/x-python",
  ".html": "text/html",
  ".css": "text/css",
  ".json": "application/json",
  ".xml": "application/xml",
  ".sql": "text/x-sql",
  ".sh": "text/x-sh",
  ".yaml": "text/yaml",
  ".yml": "text/yaml",
  ".java": "text/x-java",
  ".cpp": "text/x-c++src",
  ".c": "text/x-c",
  ".h": "text/x-csrc",
  ".php": "text/x-php",
  ".rb": "text/x-ruby",
  ".go": "text/x-go",
  ".rs": "text/x-rustsrc",
  ".ts": "text/typescript",
  ".vue": "text/x-vue",
  ".jsx": "text/jsx",
  ".tsx": "text/tsx",
};
